config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'sessions/registrations' }


  get '/' => 'home#home', as: 'home'
  get '/leagues/mlb' => 'leagues#mlb', as: 'mlb'
  get '/leagues/nba' => 'leagues#nba', as: 'nba'
  get '/leagues/nfl' => 'leagues#nfl', as: 'nfl'
  get '/leagues/nhl' => 'leagues#nhl', as: 'nhl'
  get '/leagues/mlb/boxscores' => 'leagues#mlb_boxscores'
  get '/leagues/nba/boxscores' => 'leagues#nba_boxscores'
  get '/leagues/nfl/boxscores' => 'leagues#nfl_boxscores'
  get '/leagues/nhl/boxscores' => 'leagues#nhl_boxscores'
  get '/leagues/nhl/scrape' => 'leagues#scrape_nhl'
  get '/leagues/nba/scrape' => 'leagues#scrape_nba'
  get '/leagues/nfl/scrape' => 'leagues#scrape_nfl'
  resources :users, only: [:edit, :update]
  resources :user_teams, only: [:edit, :update, :create]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :team
  belongs_to :league

  validates :title, uniqueness: true 
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  has_many :user_leagues
  has_many :users, through: :user_leagues
  has_many :articles
end

app/models/mlb_boxscore.rb
class MlbBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/nba_boxscore.rb
class NbaBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'

end

app/models/nfl_boxscore.rb
class NflBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/nhl_boxscore.rb
class NhlBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :user_teams
  has_many :users, through: :user_teams
  has_many :articles
  belongs_to :league
  has_many :mlb_boxscores
  has_many :nba_boxscores
  has_many :nfl_boxscores
  has_many :nhl_boxscores


  def self.nba_teams
    League.find_by(abbreviation: "NBA").teams.sort_by { |team| team.team_name}
  end

  def self.nfl_teams
    League.find_by(abbreviation: "NFL").teams.sort_by { |team| team.team_name}
  end

  def self.nhl_teams
    League.find_by(abbreviation: "NHL").teams.sort_by { |team| team.team_name}
  end

  def self.mlb_teams
    League.find_by(abbreviation: "MLB").teams.sort_by { |team| team.team_name}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_teams
  has_many :teams, through: :user_teams
  has_many :user_leagues
  has_many :leagues, through: :user_leagues
end

app/models/user_league.rb
class UserLeague < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_user

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name << :avatar
  end

  def set_user
    @current_user = current_user if user_signed_in?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end


end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :last_updated

  def nba
    articles = ArticleFinder.new(find_league_object("NBA"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 2)
  end

  def nhl
    articles = ArticleFinder.new(find_league_object("NHL"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 4)
  end

  def mlb
    articles = ArticleFinder.new(find_league_object("MLB"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 1)
  end

  def nfl
    articles = ArticleFinder.new(find_league_object("NFL"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 3)
  end


  def mlb_boxscores
    boxscores =  MlbBoxscore.where(game_date: Date.today - 1.day)
    render :json => boxscore_helper(boxscores)
  end

  def nfl_boxscores
    boxscores =  NflBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def nba_boxscores
    boxscores =  NbaBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def nhl_boxscores
    boxscores =  NhlBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def scrape_nhl
    scraper = Adapter::NhlScraper.new(current_user.teams.find_by(league_id: 4).team_name)
    render :json => scraper.live_scrape
  end

  def scrape_nba
    scraper = Adapter::NbaScraper.new(current_user.teams.find_by(league_id: 2).team_name)
    render :json => scraper.live_scrape
  end

  def scrape_nfl
    city = current_user.teams.find_by(league_id: 3).city.gsub(" ","")
    team_name = current_user.teams.find_by(league_id: 3).team_name.gsub(" ","")
    abbreviation = current_user.teams.find_by(league_id: 3).abbreviation
    scraper = Adapter::NflScraper.new(city, team_name, abbreviation)
    render :json => scraper.live_scrape
  end

  private

  def last_updated
    @last_updated = Article.last.created_at
  end

  def boxscore_helper(boxscores)
    outbound_array = []
    boxscores.each do |box|
      hash = {boxscore: box, home_team: box.home_team, away_team: box.away_team}
      outbound_array << hash
    end
    outbound_array
  end

  def set_articles(articles)
    @cbs_articles = articles.five_most_recent("cbs")
    @espn_articles = articles.five_most_recent("espn")
    @yahoo_articles = articles.five_most_recent("yahoo")
  end

  def find_league_object(league)
    League.includes(:articles).find_by(abbreviation: league)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/user_teams_controller.rb
class UserTeamsController < ApplicationController

  def edit
    @user = current_user
    @nba_teams = Team.nba_teams
    @nhl_teams = Team.nhl_teams
    @mlb_teams = Team.mlb_teams
    @nfl_teams = Team.nfl_teams
  end

  def update
    current_user.update(user_teams_params)
    redirect_to home_path
  end


  private

  def user_teams_params
    params.require(:user).permit(team_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to home_path 
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def updated_at(last_updated)
    distance_of_time_in_words(Time.now, last_updated)
  end

  def nfl_images
    ["lambeau", "nyg-car", "nyg-rb"].sample
  end

  def nhl_images
    ["nyr-goalie", "nyr-nyi", "hockey-arena", "mcdonagh"].sample
  end

  def baseball_images
    ["baseball-wide", "baseballs", "stadium", "baseball-home"].sample
  end

  def nba_images
    ["jordan", "basketball"].sample
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/leagues/_card_text.html.erb
<p class="card-text text-sm-center"><%= link_to article.title, article.url, target: "_blank" %></p>

app/views/leagues/_main.html.erb
    <!-- League News -->
     <section id="league" class="intro-section">
         <h1 id="league-title"> <%= league %></h1>
         <!--ESPN-->
         <div class="card-deck-wrapper">
           <div class="card-deck">
             <div class="card">
               <br>
               <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/2000px-ESPN_wordmark.svg.png", alt: "espn logo", class: "card-img-top img-fluid img-limit center-block" %>
               <div class="card-block">
                 <h4 class="card-header">Headlines</h4>
                 <%= render partial: 'card_text', collection: @espn_articles, as: :article %>
                 <p class="card-text"><small class="text-muted">Last updated <%= updated_at(@last_updated)%> ago</small></p>
               </div>
             </div>
             <!--Yahoo-->
             <div class="card">
               <br>
               <%= image_tag "http://sportsmediareport.net/wp-content/uploads/2015/12/Yahoo-Sports-Logo.jpg", alt: "yahoo logo", class: "card-img-top img-fluid img-limit center-block" %>
               <div class="card-block">
                 <h4 class="card-header">Headlines</h4>
                 <%= render partial: 'card_text', collection: @yahoo_articles, as: :article %>
                 <p class="card-text"><small class="text-muted">Last updated <%= updated_at(@last_updated)%> ago</small></p>
               </div>
             </div>
             <!--CBS-->
             <div class="card">
               <br>
               <%= image_tag "http://sports.cbsimg.net/images/blogs/cbs_sports_logo.JPG", alt: "cbs sports logo", class: "card-img-top img-fluid img-limit center-block" %>
               <div class="card-block">
                 <h4 class="card-header">Headlines</h4>
                 <%= render partial: 'card_text', collection: @cbs_articles, as: :article %>
                 <p class="card-text"><small class="text-muted">Last updated <%= updated_at(@last_updated)%> ago</small></p>
               </div>
             </div>
           </div>
     </section>



     <!-- Team News -->
     <section id="team" class="contact-section" style="padding-bottom: 100px">
         <div class="container">
             <div class="row">
                 <div class="col-lg-12">
                     <h1>Team News </h1>
                 </div>
             </div>
             <br><br><br><br><br><br>
         </div>
     </section>



 <!-- <h1>Scrolling Nav</h1>
 <p><strong>Usage Instructions:</strong> Make sure to include the <code>scrolling-nav.js</code>, <code>jquery.easing.min.js</code>, and <code>scrolling-nav.css</code> files. To make a link smooth scroll to another section on the page, give the link the <code>.page-scroll</code> class and set the link target to a corresponding ID on the page.</p>
 <a class="btn btn-default page-scroll" href="#about">Click Me to Scroll Down!</a> -->

app/views/leagues/_mlb_footer.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-bottom" id="bottom-nav">

  <div class="nav navbar-nav">
    <div id='horiz-contain-1'>
      <div id='horiz-contain-2'>
        <div class="card-deck-wrapper">
          <div class="card-deck" id="boxscore-deck">
          </div><!--end card deck-->
        </div><!--end card deck wrapper-->
      </div><!-- end container 2 -->
    </div><!-- end container 1 -->
  </div><!--end footer nav-->


</nav>

<script>
$(document).ready(function(){
  $.ajax({
    url: '/leagues/mlb/boxscores',
    dataType: "JSON"
  }).done(function(response){
    var html_card_deck = ""
    var html_new_divs = ""
      response.forEach(function(game, index){
        html_card_deck += '<div class="card card-block" style="min-width: 250px" data-toggle="collapse" href="#game' + game.boxscore.id + '" aria-expanded="false" aria-controls="game' + game.boxscore.id + '"><center>' + game.home_team.team_name + ": " + game.boxscore.home_runs + "<br>" + game.away_team.team_name + ": " + game.boxscore.away_runs + "</center></div>"
        html_new_divs += '<div class="collapse width" id="game' + game.boxscore.id + '"><div class="card card-block" style="width: 20rem"><div><table class="table">'
        html_new_divs += '<strong><tr><td>' + "Teams" + '</td><td>' + "R" + '</td><td>' + "H" + '</td><td>' + "E" + '</td><td></tr></strong>'
        html_new_divs += '<tr><td>' + game.home_team.team_name + ': </td><td>' + game.boxscore.home_runs+ '</td><td>' + game.boxscore.home_hits + '</td><td>' + game.boxscore.home_errors + '</td><td></tr>'
        html_new_divs += '<tr><td>' + game.away_team.team_name + ': </td><td>' + game.boxscore.away_runs+ '</td><td>' + game.boxscore.away_hits + '</td><td>' + game.boxscore.away_errors + '</td><td></tr>'
        html_new_divs += '</table></div></div></div>'
      })
      $('#boxscore-deck').append(html_card_deck)
      $('#bottom-nav').append(html_new_divs)
  })

})
</script>

app/views/leagues/_nba_footer.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-bottom" id="bottom-nav">

  <div class="nav navbar-nav">
    <div id='horiz-contain-1'>
      <div id='horiz-contain-2'>
        <div class="card-deck-wrapper">
          <div class="card-deck" id="boxscore-deck">
          </div><!--end card deck-->
        </div><!--end card deck wrapper-->
      </div><!-- end container 2 -->
    </div><!-- end container 1 -->
  </div><!--end footer nav-->


</nav>

<script>
$(document).ready(function(){
  $.ajax({
    url: '/leagues/nba/boxscores',
    dataType: "JSON"
  }).done(function(response){
    var html_card_deck = ""
      response.forEach(function(game, index){
        html_card_deck += '<div class="card card-block" style="min-width: 250px" data-toggle="collapse" href="#game' + game.boxscore.id + '" aria-expanded="false" aria-controls="game' + game.boxscore.id + '"><center>' + game.home_team.team_name + ": " + game.boxscore.home_team_score + "<br>" + game.away_team.team_name + ": " + game.boxscore.away_team_score + "</center></div>"
      })
      $('#boxscore-deck').append(html_card_deck)
  })

})
</script>

app/views/leagues/_nfl_footer.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-bottom" id="bottom-nav">

  <div class="nav navbar-nav">
    <div id='horiz-contain-1'>
      <div id='horiz-contain-2'>
        <div class="card-deck-wrapper">
          <div class="card-deck" id="boxscore-deck">
          </div><!--end card deck-->
        </div><!--end card deck wrapper-->
      </div><!-- end container 2 -->
    </div><!-- end container 1 -->
  </div><!--end footer nav-->


</nav>

<script>
$(document).ready(function(){
  $.ajax({
    url: '/leagues/nfl/boxscores',
    dataType: "JSON"
  }).done(function(response){
    var html_card_deck = ""
      response.forEach(function(game, index){
        html_card_deck += '<div class="card card-block" style="min-width: 250px" data-toggle="collapse" href="#game' + game.boxscore.id + '" aria-expanded="false" aria-controls="game' + game.boxscore.id + '"><center>' + game.home_team.team_name + ": " + game.boxscore.home_team_score + "<br>" + game.away_team.team_name + ": " + game.boxscore.away_team_score + "</center></div>"
      })
      $('#boxscore-deck').append(html_card_deck)
  })

})
</script>

app/views/leagues/_nhl_footer.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-bottom" id="bottom-nav">

  <div class="nav navbar-nav">
    <div id='horiz-contain-1'>
      <div id='horiz-contain-2'>
        <div class="card-deck-wrapper">
          <div class="card-deck" id="boxscore-deck">
          </div><!--end card deck-->
        </div><!--end card deck wrapper-->
      </div><!-- end container 2 -->
    </div><!-- end container 1 -->
  </div><!--end footer nav-->


</nav>

<script>
$(document).ready(function(){
  $.ajax({
    url: '/leagues/nhl/boxscores',
    dataType: "JSON"
  }).done(function(response){
    var html_card_deck = ""
      response.forEach(function(game, index){
        html_card_deck += '<div class="card card-block" style="min-width: 250px" data-toggle="collapse" href="#game' + game.boxscore.id + '" aria-expanded="false" aria-controls="game' + game.boxscore.id + '"><center>' + game.home_team.team_name + ": " + game.boxscore.home_team_score + "<br>" + game.away_team.team_name + ": " + game.boxscore.away_team_score + "</center></div>"
      })
      $('#boxscore-deck').append(html_card_deck)
  })

})
</script>

app/views/leagues/_splash.html.erb
<section id="top" class="splash-image">
    <%= image_tag image, class: "img-fluid img-splash"%>
</section>

app/views/leagues/mlb.html.erb
<%= render partial: 'splash', locals: { image: baseball_images }%>

<%= render partial: 'main', locals: {
                                      league: "MLB",
                                      cbs_articles: @cbs_articles,
                                      espn_articles: @espn_articles,
                                      yahoo_articles: @yahoo_articles
                                    } %>
<%= render partial: 'mlb_footer' %>

<script>
  $(document).ready(function(){
    var html = ""
    $.ajax({
      url: "http://mlb.com/gen/<%= @team.abbreviation.downcase %>/news/headlines.json",
      dataType: "JSON"
    }).done(function(response){

      var j = 10
      if (response.members.length < i){
        j = response.members.length
      }

      html += '<div class="card-deck-wrapper"><div class="card-deck">'
      html += '<div class="card"><br>'
      html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      html += '<div class="card-block"><h4 class="card-header">Headlines</h4><center><table><tr><td style="padding: 0px 40px;">'

      for(var i = 0; i < (j - 5); i++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px"><a target="_blank" href="' +   response.members[i].url + '">' +   response.members[i].headline + '</a></p></center>'
      }
      html += '</td><td style="padding: 0px 40px;">'
      // html += '</div></div>'
      // html += '<div class="card"><br>'
      // html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      // html += '<div class="card-block"><h4 class="card-header">Headlines</h4>'
      for(var k = 5; k < j; k++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px"><a target="_blank" href="' +  response.members[k].url + '">' +   response.members[k].headline + '</a></p></center>'
      }
      html += '</td></tr></table></center></div></div></div></div>'
      $('div .col-lg-12').append(html)
    })
  })
</script>

app/views/leagues/nba.html.erb
<%= render partial: 'splash', locals: { image: nba_images }%>

<%= render partial: 'main', locals: {
                                      league: "NBA",
                                      cbs_articles: @cbs_articles,
                                      espn_articles: @espn_articles,
                                      yahoo_articles: @yahoo_articles
                                    } %>

<%= render partial: 'nba_footer' %>
<script>
  $(document).ready(function(){
    var html = ""
    $.ajax({
      url: "/leagues/nba/scrape",
      dataType: "JSON"
    }).done(function(response){
      var j = 8
      if (response.length < i){
        j = response.length
      }

      html += '<div class="card-deck-wrapper"><div class="card-deck">'
      html += '<div class="card"><br>'
      html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      html += '<div class="card-block"><h4 class="card-header">Headlines</h4><table><tr><td style="padding: 0px 40px;">'
      for(var i = 0; i < (j - 4); i++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px"><a target="_blank" href="' +   response[i].link + '">' +   response[i].headline + '</a></p></center>'
      }
      html += '</td><td style="padding: 0px 40px;">'
      // html += '</div></div>'
      // html += '<div class="card"><br>'
      // html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      // html += '<div class="card-block"><h4 class="card-header">Headlines</h4>'
      for(var k = 5; k < j; k++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px"><a target="_blank" href="' +  response[k].link + '">' +   response[k].headline + '</a></p></center>'
      }
      html += '</td></tr></table></div></div></div></div>'
      $('div .col-lg-12').append(html)
    })
  })
</script>

app/views/leagues/nfl.html.erb
<%= render partial: 'splash', locals: { image: nfl_images }%>

<%= render partial: 'main', locals: {
                                      league: "NFL",
                                      cbs_articles: @cbs_articles,
                                      espn_articles: @espn_articles,
                                      yahoo_articles: @yahoo_articles
                                    } %>



<%= render partial: 'nfl_footer' %>
<script>
$(document).ready(function(){
  var html = ""
  $.ajax({
    url: "/leagues/nfl/scrape",
    dataType: "JSON"
  }).done(function(response){
    var j = 10
    if (response.length < i){
      j = response.length
    }

    html += '<div class="card-deck-wrapper"><div class="card-deck">'
    html += '<div class="card"><br>'
    html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
    html += '<div class="card-block"><h4 class="card-header">Headlines</h4><table><tr><td style="padding: 0px 40px;">'
    for(var i = 0; i < (j - 5); i++ ){
      html += '<center><p class="card-text" style="padding: 8px 0px;"><a target="_blank" href="' +   response[i].link + '">' +   response[i].headline + '</a></p></center>'
    }
    html += '</td><td style="padding: 0px 40px;">'
    // html += '</div></div>'
    // html += '<div class="card"><br>'
    // html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
    // html += '<div class="card-block"><h4 class="card-header">Headlines</h4>'
    for(var k = 5; k < j; k++ ){
      html += '<center><p class="card-text" style="padding: 8px 0px;"><a target="_blank" href="' +  response[k].link + '">' +   response[k].headline + '</a></p></center>'
    }
    html += '</td></tr></table></div></div></div></div>'
    $('div .col-lg-12').append(html)
  })
})
</script>

app/views/leagues/nhl.html.erb
<%= render partial: 'splash', locals: { image: nhl_images }%>

<%= render partial: 'main', locals: {
                                      league: "NHL",
                                      cbs_articles: @cbs_articles,
                                      espn_articles: @espn_articles,
                                      yahoo_articles: @yahoo_articles
                                    } %>

<%= render partial: 'nhl_footer' %>
<script>
  $(document).ready(function(){
    var html = ""
    $.ajax({
      url: "/leagues/nhl/scrape",
      dataType: "JSON"
    }).done(function(response){

      var j = 10
      if (response.length < i){
        j = response.length
      }

      html += '<div class="card-deck-wrapper"><div class="card-deck">'
      html += '<div class="card"><br>'
      html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      html += '<div class="card-block"><h4 class="card-header">Headlines</h4><table><tr><td style="padding: 0px 40px;">'
      for(var i = 0; i < (j - 5); i++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px;"><a target="_blank" href="' +   response[i].link + '">' +   response[i].headline + '</a></p></center>'
      }
      html += '</td><td style="padding: 0px 40px;">'
      // html += '</div></div>'
      // html += '<div class="card"><br>'
      // html += '<img class="card-img-top img-fluid img-limit center-block" src=<%=@team.logo%>>'
      // html += '<div class="card-block"><h4 class="card-header">Headlines</h4>'
      for(var k = 5; k < j; k++ ){
        html += '<center><p class="card-text" style="padding: 8px 0px;"><a target="_blank" href="' +  response[k].link + '">' +   response[k].headline + '</a></p></center>'
      }
      html += '</td></tr></table></div></div></div></div>'
      $('div .col-lg-12').append(html)
    })
  })
</script>

app/views/user_teams/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <h4>Choose Your Favorite Team for Each League</h4>
    <%= form_tag(user_team_path, method: "patch") do %>
    <table class="table table-striped">
      <tr>
        <td>
          <strong> MLB: </strong>
        </td>
        <td>
          <select name="user[team_ids][]">
            <% @mlb_teams.each do |team| %>
            <option value='<%= team.id %>' <%= "selected" if @user.team_ids.include?(team.id)%> ><%= team.team_name%></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>
          <strong> NBA: </strong>
        </td>
        <td>
          <select name="user[team_ids][]">
            <% @nba_teams.each do |team| %>
            <option value='<%= team.id %>' <%= "selected" if @user.team_ids.include?(team.id)%> ><%= team.team_name%></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>
          <strong> NFL: </strong>
        </td>
        <td>
          <select name="user[team_ids][]">
            <% @nfl_teams.each do |team| %>
            <option value='<%= team.id %>' <%= "selected" if @user.team_ids.include?(team.id)%> ><%= team.team_name%></option>
            <% end %>
          </select>
        </td>
      </tr>
      <tr>
        <td>
          <strong> NHL: </strong>
        </td>
        <td>
          <select name="user[team_ids][]">
            <% @nhl_teams.each do |team| %>
            <option value='<%= team.id %>' <%= "selected" if @user.team_ids.include?(team.id)%> ><%= team.team_name%></option>
            <% end %>
          </select>
        </td>
      </tr>
    </table>

      <%= button_tag(type: "submit", class: "btn btn-info") do %>
          Update Teams
      <%end%>
      <% end %>
</div>

app/views/users/edit.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <h1> Profile </h1>
  <%= form_for(@user) do |f| %>
    <br>
    <fieldset class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %><br>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :avatar %>
      <%= f.text_field :avatar, class: "form-control"%><br>
    </fieldset>
    <div class="actions">
      <%= f.submit "Update Profile", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>