config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'sessions/registrations' }


  get '/' => 'home#home', as: 'home'
  get '/leagues/mlb' => 'leagues#mlb', as: 'mlb'
  get '/leagues/nba' => 'leagues#nba', as: 'nba'
  get '/leagues/nfl' => 'leagues#nfl', as: 'nfl'
  get '/leagues/nhl' => 'leagues#nhl', as: 'nhl'
  get '/leagues/mlb/boxscores' => 'leagues#mlb_boxscores'
  get '/leagues/nba/boxscores' => 'leagues#nba_boxscores'
  get '/leagues/nfl/boxscores' => 'leagues#nfl_boxscores'
  get '/leagues/nhl/boxscores' => 'leagues#nhl_boxscores'
  get '/leagues/nhl/scrape' => 'leagues#scrape_nhl'
  get '/leagues/nba/scrape' => 'leagues#scrape_nba'
  get '/leagues/nfl/scrape' => 'leagues#scrape_nfl'
  resources :users, only: [:edit, :update]
  resources :user_teams, only: [:edit, :update, :create]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :team
  belongs_to :league

  validates :title, uniqueness: true 
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :teams
  has_many :user_leagues
  has_many :users, through: :user_leagues
  has_many :articles
end

app/models/mlb_boxscore.rb
class MlbBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/nba_boxscore.rb
class NbaBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'

end

app/models/nfl_boxscore.rb
class NflBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/nhl_boxscore.rb
class NhlBoxscore < ActiveRecord::Base
  belongs_to :home_team, :class_name => 'Team'
  belongs_to :away_team, :class_name => 'Team'
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :user_teams
  has_many :users, through: :user_teams
  has_many :articles
  belongs_to :league
  has_many :mlb_boxscores
  has_many :nba_boxscores
  has_many :nfl_boxscores
  has_many :nhl_boxscores


  def self.nba_teams
    League.find_by(abbreviation: "NBA").teams.sort_by { |team| team.team_name}
  end

  def self.nfl_teams
    League.find_by(abbreviation: "NFL").teams.sort_by { |team| team.team_name}
  end

  def self.nhl_teams
    League.find_by(abbreviation: "NHL").teams.sort_by { |team| team.team_name}
  end

  def self.mlb_teams
    League.find_by(abbreviation: "MLB").teams.sort_by { |team| team.team_name}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_teams
  has_many :teams, through: :user_teams
  has_many :user_leagues
  has_many :leagues, through: :user_leagues
end

app/models/user_league.rb
class UserLeague < ActiveRecord::Base
  belongs_to :user
  belongs_to :league
end

app/models/user_team.rb
class UserTeam < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end


end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :last_updated

  def nba
    articles = ArticleFinder.new(find_league_object("NBA"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 2)
  end

  def nhl
    articles = ArticleFinder.new(find_league_object("NHL"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 4)
  end

  def mlb
    articles = ArticleFinder.new(find_league_object("MLB"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 1)
  end

  def nfl
    articles = ArticleFinder.new(find_league_object("NFL"))
    set_articles(articles)
    @team = current_user.teams.find_by(league_id: 3)
  end


  def mlb_boxscores
    boxscores =  MlbBoxscore.where(game_date: Date.today - 1.day)
    render :json => boxscore_helper(boxscores)
  end

  def nfl_boxscores
    boxscores =  NflBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def nba_boxscores
    boxscores =  NbaBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def nhl_boxscores
    boxscores =  NhlBoxscore.all
    render :json => boxscore_helper(boxscores)
  end

  def scrape_nhl
    scraper = Adapter::NhlScraper.new(current_user.teams.find_by(league_id: 4).team_name)
    render :json => scraper.live_scrape
  end

  def scrape_nba
    scraper = Adapter::NbaScraper.new(current_user.teams.find_by(league_id: 2).team_name)
    render :json => scraper.live_scrape
  end

  def scrape_nfl
    city = current_user.teams.find_by(league_id: 3).city.gsub(" ","")
    team_name = current_user.teams.find_by(league_id: 3).team_name.gsub(" ","")
    abbreviation = current_user.teams.find_by(league_id: 3).abbreviation
    scraper = Adapter::NflScraper.new(city, team_name, abbreviation)
    render :json => scraper.live_scrape
  end

  private

  def last_updated
    @last_updated = Article.last.created_at
  end

  def boxscore_helper(boxscores)
    outbound_array = []
    boxscores.each do |box|
      hash = {boxscore: box, home_team: box.home_team, away_team: box.away_team}
      outbound_array << hash
    end
    outbound_array
  end

  def set_articles(articles)
    @cbs_articles = articles.five_most_recent("cbs")
    @espn_articles = articles.five_most_recent("espn")
    @yahoo_articles = articles.five_most_recent("yahoo")
  end

  def find_league_object(league)
    League.includes(:articles).find_by(abbreviation: league)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to home_path 
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def updated_at(last_updated)
    distance_of_time_in_words(Time.now, last_updated)
  end

  def nfl_images
    ["lambeau", "nyg-car", "nyg-rb"].sample
  end

  def nhl_images
    ["nyr-goalie", "nyr-nyi", "hockey-arena", "mcdonagh"].sample
  end

  def baseball_images
    ["baseball-wide", "baseballs", "stadium", "baseball-home"].sample
  end

  def nba_images
    ["jordan", "basketball"].sample
  end

end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-light bg-faded navbar-fixed-bottom" id="bottom-nav">

  <div class="nav navbar-nav">
    <div id='horiz-contain-1'>
      <div id='horiz-contain-2'>
        <div class="card-deck-wrapper">
          <div class="card-deck" id="boxscore-deck">
          </div><!--end card deck-->
        </div><!--end card deck wrapper-->
      </div><!-- end container 2 -->
    </div><!-- end container 1 -->
  </div><!--end footer nav-->


</nav>

<script>
$(document).ready(function(){
  $.ajax({
    url: '/leagues/mlb/boxscores',
    dataType: "JSON"
  }).done(function(response){
    var html_card_deck = ""
    var html_new_divs = ""
      response.forEach(function(game, index){
        html_card_deck += '<div class="card card-block" style="min-width: 250px" data-toggle="collapse" href="#game' + game.boxscore.id + '" aria-expanded="false" aria-controls="game' + game.boxscore.id + '"><center>' + game.home_team.team_name + ": " + game.boxscore.home_runs + "<br>" + game.away_team.team_name + ": " + game.boxscore.away_runs + "</center></div>"
        html_new_divs += '<div class="collapse" id="game' + game.boxscore.id + '"><div class="card card-block"><div><table>'
        html_new_divs += '<tr><td>' + "Teams" + '</td><td>' + "R" + '</td><td>' + "H" + '</td><td>' + "E" + '</td><td></tr>'
        html_new_divs += '<tr><td>' + game.home_team.team_name + ': </td><td>' + game.boxscore.home_runs+ '</td><td>' + game.boxscore.home_hits + '</td><td>' + game.boxscore.home_errors + '</td><td></tr>'
        html_new_divs += '<tr><td>' + game.away_team.team_name + ': </td><td>' + game.boxscore.away_runs+ '</td><td>' + game.boxscore.away_hits + '</td><td>' + game.boxscore.away_errors + '</td><td></tr>'
        html_new_divs += '</table></div></div></div>'
      })
      $('#boxscore-deck').append(html_card_deck)
      $('#bottom-nav').append(html_new_divs)
  })

})
</script>

app/views/layouts/_home_nav.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">

  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <%= link_to image_tag("sporthub_logo", width: '150', height: '100'), home_path, class: "navbar-brand" %>

  <div class="collapse navbar-toggleable-xs nav-center" id="exCollapsingNavbar2">
    <div class="pull-sm-right">
      <img class="avatar-nav" src="<%=@current_user.avatar%>">
    </div>
    <div class="dropdown pull-sm-right tiny-pad">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= @current_user.name %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <%= button_to "Teams", edit_user_team_path(@current_user), method: "get", class: "dropdown-item" %>
        <%= button_to "Settings", edit_user_path(@current_user), method: "get", class: "dropdown-item" %>
        <%= button_to "Logout", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
      </div>
    </div>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%= link_to "NBA", nba_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "MLB", mlb_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "NFL", nfl_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "NHL", nhl_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_navbar_logged_in.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">

  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <%= link_to image_tag("sporthub_logo", width: '150', height: '100'), home_path, class: "navbar-brand" %>

  <div class="collapse navbar-toggleable-xs nav-center" id="exCollapsingNavbar2">
    <div class="pull-sm-right">
      <img class="avatar-nav" src="<%=@current_user.avatar%>">
    </div>
    <div class="dropdown pull-sm-right tiny-pad">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%= @current_user.name %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <%= button_to "Teams", edit_user_team_path(@current_user), method: "get", class: "dropdown-item" %>
        <%= button_to "Settings", edit_user_path(@current_user), method: "get", class: "dropdown-item" %>
        <%= button_to "Logout", destroy_user_session_path, method: "delete", class: "dropdown-item" %>
      </div>
    </div>
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%= link_to "NBA", nba_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "MLB", mlb_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "NFL", nfl_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "NHL", nhl_path, class: "nav-link" %>
      </li>
      <!-- Scrollers  -->
      <li class="nav-item pull-sm-right tiny-pad">
        <a class="nav-link page-scroll" href="#team">Team News</a>
      </li>
      <li class="nav-item pull-sm-right">
        <a class="nav-link page-scroll" href="#league">League News<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item pull-sm-right">
        <a class="nav-link page-scroll" href="#top">Top</span></a>
      </li>
    </ul>


  </div>
</nav>

app/views/layouts/_navbar_not_logged_in.html.erb
<nav class="navbar navbar-top navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <%= link_to image_tag("sporthub_logo", width: '150', height: '100'), home_path, class: "navbar-brand" %>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
  </div>
  <ul class="nav nav-inline pull-md-right">
    <li class="nav-link">
      <%= link_to "Login", new_user_session_path %>
    </li>
  <ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sport Hub</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <% if user_signed_in? && request.fullpath == "/" %>
      <%= render 'layouts/home_nav' %>
    <% elsif user_signed_in? %>
      <%= render 'layouts/navbar_logged_in' %>
    <% else %>
      <%= render 'layouts/navbar_not_logged_in' %>
    <% end %>

    <%= yield %>


  </body>
</html>